/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_ClickMeal;

import br.edu.ifmg.sabara.poo2.a2017.modelo.Adm;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author IFMG
 */
public class Tela_Busca extends javax.swing.JFrame {
    Adm admin=new Adm();
    private static int numeroIngredientes;
    /**
     * Creates new form Tela_Busca
     */
    public Tela_Busca() {
        numeroIngredientes = 3;
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Botão_buscar = new javax.swing.JButton();
        Botão_novoIng = new javax.swing.JButton();
        Label_ing_1 = new javax.swing.JLabel();
        Label_ing_2 = new javax.swing.JLabel();
        Label_ing_3 = new javax.swing.JLabel();
        jTextField_ing1 = new javax.swing.JTextField();
        jTextField_ing2 = new javax.swing.JTextField();
        jTextField_ing3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        Botão_buscar.setBackground(new java.awt.Color(51, 51, 51));
        Botão_buscar.setFont(new java.awt.Font("Albertus Medium", 1, 18)); // NOI18N
        Botão_buscar.setText("Buscar Receitas");
        Botão_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(Botão_buscar);
        Botão_buscar.setBounds(90, 350, 170, 80);

        Botão_novoIng.setBackground(new java.awt.Color(51, 51, 51));
        Botão_novoIng.setFont(new java.awt.Font("Albertus Medium", 1, 14)); // NOI18N
        Botão_novoIng.setText("Adicionar outro ingrediente");
        Botão_novoIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_novoIngActionPerformed(evt);
            }
        });
        jPanel1.add(Botão_novoIng);
        Botão_novoIng.setBounds(50, 190, 260, 30);

        Label_ing_1.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        Label_ing_1.setText("<html><center>Ingrediente 1: </center></html>");
        jPanel1.add(Label_ing_1);
        Label_ing_1.setBounds(50, 60, 90, 30);

        Label_ing_2.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        Label_ing_2.setText("<html><center>Ingrediente 2: </center></html>");
        jPanel1.add(Label_ing_2);
        Label_ing_2.setBounds(50, 100, 90, 30);

        Label_ing_3.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        Label_ing_3.setText("<html><center>Ingrediente 3: </center></html>");
        jPanel1.add(Label_ing_3);
        Label_ing_3.setBounds(50, 140, 90, 30);

        jTextField_ing1.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jPanel1.add(jTextField_ing1);
        jTextField_ing1.setBounds(170, 60, 140, 30);

        jTextField_ing2.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jPanel1.add(jTextField_ing2);
        jTextField_ing2.setBounds(170, 100, 140, 30);

        jTextField_ing3.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jTextField_ing3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ing3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_ing3);
        jTextField_ing3.setBounds(170, 140, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(372, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ing3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ing3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ing3ActionPerformed

    private void Botão_novoIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_novoIngActionPerformed

        numeroIngredientes++;
        int posicaoY = 20 + (numeroIngredientes * 40);
        if(numeroIngredientes==7){
            Botão_novoIng.setVisible(false);
            JLabel Label_ing_new = new javax.swing.JLabel();
            Label_ing_new.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
            Label_ing_new.setText("Ingrediente " +numeroIngredientes +":" );
            Label_ing_new.setBounds(50, posicaoY, 90, 30);

            JTextField jTextField_new = new javax.swing.JTextField();
            jTextField_new.setBounds(170, posicaoY, 140, 30);

            jPanel1.add(Label_ing_new);
            jPanel1.add(jTextField_new);

            Botão_novoIng.setLocation(50, (int)(this.Botão_novoIng.getY()+30));
            jPanel1.repaint();
        }
        else{

            JLabel Label_ing_new = new javax.swing.JLabel();
            Label_ing_new.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
            Label_ing_new.setText("Ingrediente " +numeroIngredientes +":" );
            Label_ing_new.setBounds(50, posicaoY, 90, 30);

            JTextField jTextField_new = new javax.swing.JTextField();
            jTextField_new.setFont(new java.awt.Font("Albertus Medium", 1, 12));
            jTextField_new.setBounds(170, posicaoY, 140, 30);

            jPanel1.add(Label_ing_new);
            jPanel1.add(jTextField_new);

            Botão_novoIng.setLocation(50, (int)(this.Botão_novoIng.getY()+40));
            jPanel1.repaint();
        }
    }//GEN-LAST:event_Botão_novoIngActionPerformed

    private void Botão_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_buscarActionPerformed
      int [] vet = null;
       vet[0]= Adm.getBanco().IndiceIngrede(jTextField_ing1.getText());
       vet[1]=Adm.getBanco().IndiceIngrede(jTextField_ing2.getText());
       vet[2]=Adm.getBanco().IndiceIngrede(jTextField_ing3.getText());
       
    }//GEN-LAST:event_Botão_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Busca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Busca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botão_buscar;
    private javax.swing.JButton Botão_novoIng;
    private javax.swing.JLabel Label_ing_1;
    private javax.swing.JLabel Label_ing_2;
    private javax.swing.JLabel Label_ing_3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_ing1;
    private javax.swing.JTextField jTextField_ing2;
    private javax.swing.JTextField jTextField_ing3;
    // End of variables declaration//GEN-END:variables
}
