/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_ClickMeal;

import javax.swing.JOptionPane;

/**
 *
 * @author IFMG
 */
public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_adm
     */
    public Tela_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_login = new javax.swing.JLabel();
        Label_senha = new javax.swing.JLabel();
        Text_login = new javax.swing.JTextField();
        jButton_Login = new javax.swing.JButton();
        jButton_Sair = new javax.swing.JButton();
        jPass_senha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        Label_login.setFont(new java.awt.Font("Albertus Medium", 1, 14)); // NOI18N
        Label_login.setText("Login:");
        jPanel1.add(Label_login);
        Label_login.setBounds(62, 118, 58, 23);

        Label_senha.setFont(new java.awt.Font("Albertus Medium", 1, 14)); // NOI18N
        Label_senha.setText("Senha:");
        jPanel1.add(Label_senha);
        Label_senha.setBounds(60, 150, 60, 25);

        Text_login.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        Text_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_loginActionPerformed(evt);
            }
        });
        jPanel1.add(Text_login);
        Text_login.setBounds(130, 110, 130, 30);

        jButton_Login.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Login.setFont(new java.awt.Font("Albertus Medium", 1, 18)); // NOI18N
        jButton_Login.setText("Entrar");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Login);
        jButton_Login.setBounds(130, 200, 100, 60);

        jButton_Sair.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Sair.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Sair);
        jButton_Sair.setBounds(140, 280, 55, 25);

        jPass_senha.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jPanel1.add(jPass_senha);
        jPass_senha.setBounds(130, 150, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 490);

        setSize(new java.awt.Dimension(372, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
        Tela_Inicial ini = new Tela_Inicial();
        ini.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_SairActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        if(autenticar(Text_login.getText(), jPass_senha.getText())){
            Tela_MenuAdm tela = new Tela_MenuAdm();
            tela.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Login Inválido");
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void Text_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_loginActionPerformed

    private boolean autenticar(String user, String pass){
        if((user.equals("yallen")) && (pass.equals("1194"))){
            return true;
        }
        else if((user.equals("salgadinho")) && (pass.equals("katinguele"))){
            return true;
        }
        else if((user.equals("a")) && (pass.equals("a"))){
            return true;
        }
        else if((user.equals("cabelodeboneca")) && (pass.equals("feministanemehgente"))){
            return true;
        }
        else if((user.equals("fofinho")) && (pass.equals("scoralickS2"))){
            return true;
        }
        else
            return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_login;
    private javax.swing.JLabel Label_senha;
    private javax.swing.JTextField Text_login;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPass_senha;
    // End of variables declaration//GEN-END:variables
}
