/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_ClickMeal;

import br.edu.ifmg.sabara.poo2.a2017.modelo.Receitas;

/**
 *
 * @author IFMG
 */
public class Tela_DetRec extends javax.swing.JFrame {
    Receitas receita;
    
    
    public Tela_DetRec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_rec = new javax.swing.JLabel();
        jTextField_rec = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_receitas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_descReceita = new javax.swing.JTextArea();
        jButton_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 20, 120, 120);

        jLabel_rec.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jLabel_rec.setText("Receita");
        jPanel1.add(jLabel_rec);
        jLabel_rec.setBounds(10, 145, 80, 20);

        jTextField_rec.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jPanel1.add(jTextField_rec);
        jTextField_rec.setBounds(10, 170, 250, 30);

        jButton_buscar.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_buscar);
        jButton_buscar.setBounds(270, 170, 80, 30);

        jList_receitas.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jList_receitas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item1", "Item2", "item3", ".", ".", ". ", "Item n" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList_receitas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 340, 90);

        jTextArea_descReceita.setColumns(20);
        jTextArea_descReceita.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jTextArea_descReceita.setLineWrap(true);
        jTextArea_descReceita.setRows(5);
        jTextArea_descReceita.setText(" /* Aqui ficara a receita selecionada acima */");
        jScrollPane2.setViewportView(jTextArea_descReceita);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 310, 340, 130);

        jButton_back.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_back.setText("Voltar");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_back);
        jButton_back.setBounds(130, 450, 67, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 490);

        setSize(new java.awt.Dimension(372, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        Tela_MenuAdm tela = new Tela_MenuAdm();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        receita=new Receitas();
        receita.setNome(jTextField_rec.getText());
        receita=receita.detalhes(receita.getNome());
        jTextArea_descReceita.setText(receita.getModPreparo());
        
    }//GEN-LAST:event_jButton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_DetRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_DetRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_DetRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_DetRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_DetRec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JLabel jLabel_rec;
    private javax.swing.JList<String> jList_receitas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_descReceita;
    private javax.swing.JTextField jTextField_rec;
    // End of variables declaration//GEN-END:variables
}
