/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_ClickMeal;

/**
 *
 * @author IFMG
 */
public class Tela_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    public Tela_Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_ClickMeal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Botão_Iniciar = new javax.swing.JButton();
        Botão_adm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        Logo_ClickMeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_clickmeal/Logo11corte.png"))); // NOI18N
        getContentPane().add(Logo_ClickMeal);
        Logo_ClickMeal.setBounds(70, 20, 220, 280);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        Botão_Iniciar.setBackground(new java.awt.Color(51, 51, 51));
        Botão_Iniciar.setFont(new java.awt.Font("Albertus Medium", 1, 18)); // NOI18N
        Botão_Iniciar.setText("<html><center>Iniciar <br> Gostosuras </center></html>");
        Botão_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_IniciarActionPerformed(evt);
            }
        });
        jPanel1.add(Botão_Iniciar);
        Botão_Iniciar.setBounds(100, 330, 150, 70);

        Botão_adm.setBackground(new java.awt.Color(51, 51, 51));
        Botão_adm.setFont(new java.awt.Font("Albertus Medium", 0, 3)); // NOI18N
        Botão_adm.setText("Admin");
        Botão_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botão_admActionPerformed(evt);
            }
        });
        jPanel1.add(Botão_adm);
        Botão_adm.setBounds(0, 480, 40, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 490);

        setSize(new java.awt.Dimension(372, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Botão_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_IniciarActionPerformed
       Tela_Busca tela = new Tela_Busca();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_Botão_IniciarActionPerformed

    private void Botão_admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botão_admActionPerformed
        Tela_Login tela = new Tela_Login();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_Botão_admActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tela_Inicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botão_Iniciar;
    private javax.swing.JButton Botão_adm;
    private javax.swing.JLabel Logo_ClickMeal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
