
package interface_ClickMeal;


public class Tela_MenuAdm extends javax.swing.JFrame {

    
    public Tela_MenuAdm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_RemovIng = new javax.swing.JButton();
        jButton_AddIng = new javax.swing.JButton();
        jButton_ExibBanc = new javax.swing.JButton();
        jButton_RemovRec = new javax.swing.JButton();
        jButton_ExibLiv = new javax.swing.JButton();
        jButton_DetRec = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_AddRec = new javax.swing.JButton();
        jLabel_Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        jButton_RemovIng.setFont(new java.awt.Font("Albertus Medium", 1, 11)); // NOI18N
        jButton_RemovIng.setText("Remove Ingrediente");
        jButton_RemovIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemovIngActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_RemovIng);
        jButton_RemovIng.setBounds(40, 350, 140, 40);

        jButton_AddIng.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_AddIng.setText("Add Ingrediente");
        jButton_AddIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddIngActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_AddIng);
        jButton_AddIng.setBounds(40, 170, 140, 40);

        jButton_ExibBanc.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_ExibBanc.setText("Exibe Banco");
        jButton_ExibBanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExibBancActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_ExibBanc);
        jButton_ExibBanc.setBounds(200, 230, 140, 40);

        jButton_RemovRec.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_RemovRec.setText("Remove Receita");
        jButton_RemovRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemovRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_RemovRec);
        jButton_RemovRec.setBounds(200, 290, 140, 40);

        jButton_ExibLiv.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_ExibLiv.setText("Exibir Livro");
        jButton_ExibLiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExibLivActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_ExibLiv);
        jButton_ExibLiv.setBounds(40, 290, 140, 40);

        jButton_DetRec.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_DetRec.setText("Detalhar Receita");
        jButton_DetRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DetRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_DetRec);
        jButton_DetRec.setBounds(40, 230, 140, 40);

        jButton_Exit.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_Exit.setText("Sair");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Exit);
        jButton_Exit.setBounds(200, 350, 140, 40);

        jButton_AddRec.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jButton_AddRec.setText("Add Receita");
        jButton_AddRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_AddRec);
        jButton_AddRec.setBounds(200, 170, 140, 40);

        jLabel_Menu.setFont(new java.awt.Font("Albertus Medium", 1, 12)); // NOI18N
        jLabel_Menu.setText("<html><center>Escolha uma opção:</center></html>");
        jPanel1.add(jLabel_Menu);
        jLabel_Menu.setBounds(120, 90, 124, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 490);

        setSize(new java.awt.Dimension(372, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddIngActionPerformed
        Tela_AddIng tela = new Tela_AddIng();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_AddIngActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        Tela_Inicial tela = new Tela_Inicial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_AddRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddRecActionPerformed
        Tela_AddRec tela = new Tela_AddRec();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_AddRecActionPerformed

    private void jButton_DetRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DetRecActionPerformed
        Tela_DetRec tela = new Tela_DetRec();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_DetRecActionPerformed

    private void jButton_ExibBancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExibBancActionPerformed
        Tela_ExibeBanco tela = new Tela_ExibeBanco();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ExibBancActionPerformed

    private void jButton_ExibLivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExibLivActionPerformed
        Tela_ExibeLivro tela = new Tela_ExibeLivro();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_ExibLivActionPerformed

    private void jButton_RemovRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemovRecActionPerformed
        Tela_RemoveRec tela = new Tela_RemoveRec();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_RemovRecActionPerformed

    private void jButton_RemovIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemovIngActionPerformed
        Tela_RemoveIng tela = new Tela_RemoveIng();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_RemovIngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_MenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddIng;
    private javax.swing.JButton jButton_AddRec;
    private javax.swing.JButton jButton_DetRec;
    private javax.swing.JButton jButton_ExibBanc;
    private javax.swing.JButton jButton_ExibLiv;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_RemovIng;
    private javax.swing.JButton jButton_RemovRec;
    private javax.swing.JLabel jLabel_Menu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
